name: Dispatch to Master Repository
on:
  push:
    branches:
      - main
      - uat
    paths-ignore:
      - 'README.md'
      - 'TEST_STATUS.md'
      - '.github/workflows/dispatch-to-master.yml'
      - '.github/workflows/test-results.yml'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      MASTER_REPO: ${{ secrets.MASTER_REPO }}
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
    steps:
      - name: Checkout Module Repository
        uses: actions/checkout@v4
      - name: Dispatch Module Updated Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MODULE_REPO_TOKEN }}
          repository: ${{ env.MASTER_REPO }}
          event-type: module-updated
          client-payload: '{"module":"${{ env.MODULE_NAME }}","commit":"${{ github.sha }}"}'
      - name: Debug Dispatch
        if: failure()
        run: |
          echo "Dispatch failed. Check MODULE_REPO_TOKEN permissions and repository access."